#!/bin/csh

setenv INS_NUM_ASCS `egrep '$SAPSYSTEMNAME|ASCS' /usr/sap/sapservices | awk '{print $4}' | grep -o '..$'`
setenv INS_NUM_PAS `egrep '$SAPSYSTEMNAME|D' /usr/sap/sapservices | awk '{print $4}' | grep -o '..$'`

sapcontrol -nr $INS_NUM_PAS -function Stop
sapcontrol -nr $INS_NUM_ASCS -function Stop 
