#!/bin/csh
psup=$(ps -ef | grep pmon | egrep -v grep | wc -l)

setenv INS_NUM_ASCS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|ASCS' | grep -v $SAPSYSTEMNAME | awk '{print $NF}' | grep -o '..$'`
setenv INS_NUM_PAS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|D' | grep -v $SAPSYSTEMNAME | awk '{print $NF}' | grep -o '..$'`


# systemctl status sapinit
# systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_ASCS.service
# systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_PAS.service

cleanipc $INS_NUM_ASCS remove
cleanipc $INS_NUM_PAS remove


for i in `ipcs -s | grep $USER | awk '{ print $2 }'`
do
echo $i
ipcrm -s $i
done


for i in `ipcs -m | grep $USER | awk '{ print $2 }'`
do
echo $i
ipcrm -m $i
done
