#!/bin/csh

setenv INS_NUM_ASCS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|ASCS' | awk '{print $NF}' | grep -o '..$'`
setenv INS_NUM_PAS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|D' | awk '{print $NF}' | grep -o '..$'`

systemctl status sapinit
systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_ASCS.service
systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_PAS.service


/usr/sap/hostctrl/exe/sapcontrol -nr $INS_NUM_ASCS -function Start
sleep 2
/usr/sap/hostctrl/exe/sapcontrol -nr $INS_NUM_PAS -function Start
