#!/bin/csh

setenv INS_NUM_ASCS `egrep '$SAPSYSTEMNAME|ASCS' /usr/sap/sapservices | awk '{print $4}' | grep -o '..$'`
setenv INS_NUM_PAS `egrep '$SAPSYSTEMNAME|D' /usr/sap/sapservices | awk '{print $4}' | grep -o '..$'`

systemctl status sapinit
systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_ASCS.service
systemctl status SAP$SAPSYSTEMNAME\_$INS_NUM_PAS.service


/usr/sap/hostctrl/exe/sapcontrol -nr $INS_NUM_ASCS -function Start
sleep 2
/usr/sap/hostctrl/exe/sapcontrol -nr $INS_NUM_PAS -function Start
