#!/bin/csh

setenv INS_NUM_ASCS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|ASCS' | grep -v $SAPSYSTEMNAME | awk '{print $NF}' | grep -o '..$'`
setenv INS_NUM_PAS `ls -la /usr/sap/$SAPSYSTEMNAME | egrep '$SAPSYSTEMNAME|D' | grep -v $SAPSYSTEMNAME | awk '{print $NF}' | grep -o '..$'`


sapcontrol -nr $INS_NUM_PAS -function Stop
sapcontrol -nr $INS_NUM_ASCS -function Stop 
